name: 'Phoenix Release'
author: 'Aaron Sutton'
description: 'Build and release a Phoenix project'
outputs:
  target:
    description: 'The target triple for which this release was compiled'
  app:
    description: 'The OTP app name and version for this release'
runs:
  using: 'node16'
  main: 'dist/index.js'
